[tool.poetry]
name = "numericalmethods"
version = "0.1.0"
description = ""
authors = ["Robertino <wp0101@inbox.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
